

export const types = {
    INICIAR_SESION: 'INICIAR_SESION',
    CERRAR_SESION: 'CERRAR_SESION',

    // ui
    AUTH_ERROR: 'AUTH_ERROR',

    // crud
    CRUD_CREATE: 'CRUD_CREATE',
    CRUD_READ: 'CRUD_READ',
    CRUD_UPDATE: 'CRUD_UPDATE',
    CRUD_DELETE: 'CRUD_DELETE',
    CRUD_UPDATE_FINALIZADO: 'CRUD_UPDATE_FINALIZADO',
}


